name: Cut a release

on:
  workflow_dispatch:
    inputs:
      newVersion:
        required: true
        description: New release version no.
        type: string

jobs:
  cut-release:
    uses: smooks/.github/.github/workflows/release.yml@master
    secrets: inherit
    with:
      newVersion: ${{ inputs.newVersion }}
